HEADING_CONTROL_WHEEL = 0
HEADING_CONTROL_ENGINE = 1
HEADING_CONTROL = HEADING_CONTROL_ENGINE

FLYING_MODE_STOP = 0
FLYING_MODE_MOVE = 1
FLYING_MODE_STABLE = 2

FLYING_DIR_FORWARD = 0
FLYING_DIR_BACK = 1
